import { s } from "@routier/core/schema";

// Identity properties within schemas
const entitySchema = s.define("entities", {
    // String identity (UUID generated by default)
    id: s.string().key().identity(),

    // Number identity (auto-incrementing if supported by plugin)
    userId: s.number().key().identity(),

    // Date identity (current timestamp)
    createdAt: s.date().key().identity(),

    // Boolean identity (always true)
    isActive: s.boolean().identity(),
}).compile();
