apiVersion: v1
kind: Secret
metadata:
  name: e2e-credentials
type: Opaque
stringData:
  postgres-password: routier-e2e
  mysql-root-password: routier-e2e
  couchdb-user: admin
  couchdb-password: routier-e2e
  s3-access-key: routier
  s3-secret-key: routier-e2e-secret
