import { createPlugin, DbChoice, ShopStore } from './store';
import { makeOrders } from './seed';

export type Timing = { step: string; ms: number; note?: string };

export type BenchResult = {
    db: DbChoice;
    count: number;
    timings: Timing[];
};

async function time(step: string, timings: Timing[], fn: () => Promise<string | void>) {
    const start = performance.now();
    const note = await fn();
    const ms = performance.now() - start;
    timings.push({ step, ms: Math.round(ms * 10) / 10, ...(typeof note === 'string' ? { note } : {}) });
}

const CHUNK = 1000;

export async function runBench(
    db: DbChoice,
    count: number,
    onProgress: (message: string) => void,
): Promise<BenchResult> {
    // A unique name per run so seeding always measures a clean database.
    const databaseName = `bench-${db}-${Date.now()}`;
    const store = new ShopStore(createPlugin(db, databaseName));
    const timings: Timing[] = [];
    const orders = makeOrders(count);

    onProgress(`Seeding ${count.toLocaleString()} orders into ${db}...`);
    await time(`Seed ${count.toLocaleString()} orders (batches of ${CHUNK})`, timings, async () => {
        for (let i = 0; i < orders.length; i += CHUNK) {
            await store.orders.addAsync(...orders.slice(i, i + CHUNK));
            await store.saveChangesAsync();
        }
    });

    onProgress('Counting...');
    await time('Count all', timings, async () => {
        const n = await store.orders.countAsync();
        return `${n.toLocaleString()} rows`;
    });

    onProgress('Reading everything...');
    await time('Read all rows', timings, async () => {
        const all = await store.orders.toArrayAsync();
        return `${all.length.toLocaleString()} rows`;
    });

    onProgress('Filtered query...');
    await time('Filter: pending orders in EU', timings, async () => {
        const rows = await store.orders
            .where(([o, p]) => o.status === p.status && o.region === p.region, { status: 'pending', region: 'eu' })
            .toArrayAsync();
        return `${rows.length.toLocaleString()} rows`;
    });

    onProgress('Sorted page...');
    await time('Page: newest 25, skip 1000', timings, async () => {
        const rows = await store.orders
            .sortDescending(o => o.createdAt)
            .skip(1000)
            .take(25)
            .toArrayAsync();
        return `${rows.length} rows`;
    });

    onProgress('Aggregating...');
    await time('Sum: revenue of paid orders', timings, async () => {
        const revenue = await store.orders
            .where(([o, p]) => o.status === p.status, { status: 'paid' })
            .sumAsync(o => o.total);
        return `$${Math.round(revenue).toLocaleString()}`;
    });

    onProgress('Point lookup...');
    await time('Find one order by email', timings, async () => {
        const target = orders[Math.floor(orders.length / 2)].email;
        const row = await store.orders.firstOrUndefinedAsync(([o, p]) => o.email === p.email, { email: target });
        return row == null ? 'MISSING' : 'found';
    });

    onProgress('Updating 500 orders...');
    await time('Update 500 orders + save', timings, async () => {
        const toShip = await store.orders
            .where(([o, p]) => o.status === p.status, { status: 'paid' })
            .take(500)
            .toArrayAsync();
        for (const order of toShip) {
            order.status = 'shipped';
        }
        await store.saveChangesAsync();
        return `${toShip.length} rows`;
    });

    return { db, count, timings };
}

/**
 * The migration itself: read every row out of one database, write it into another.
 * Identity ids are regenerated by the target; every other field copies as-is.
 */
export async function migrate(from: DbChoice, to: DbChoice, count: number, onProgress: (m: string) => void): Promise<Timing[]> {
    const timings: Timing[] = [];
    const stamp = Date.now();
    const source = new ShopStore(createPlugin(from, `migrate-src-${from}-${stamp}`));
    const target = new ShopStore(createPlugin(to, `migrate-dst-${to}-${stamp}`));

    onProgress(`Seeding source (${from})...`);
    const orders = makeOrders(count);
    for (let i = 0; i < orders.length; i += CHUNK) {
        await source.orders.addAsync(...orders.slice(i, i + CHUNK));
        await source.saveChangesAsync();
    }

    onProgress(`Copying ${from} -> ${to}...`);
    await time(`Copy ${count.toLocaleString()} rows ${from} -> ${to}`, timings, async () => {
        const rows = await source.orders.toArrayAsync();
        for (let i = 0; i < rows.length; i += CHUNK) {
            const chunk = rows.slice(i, i + CHUNK).map(({ id, ...rest }) => rest);
            await target.orders.addAsync(...chunk);
            await target.saveChangesAsync();
        }
        const copied = await target.orders.countAsync();
        return `${copied.toLocaleString()} rows in target`;
    });

    return timings;
}
