import type { ModuleLoader } from './execute';

export const MODULES: Readonly<Record<string, ModuleLoader>> = {
    'react': () => import('react'),
    'react/jsx-runtime': () => import('react/jsx-runtime'),
    '@routier/core': () => import('@routier/core'),
    '@routier/core/assertions': () => import('@routier/core/assertions'),
    '@routier/core/collections': () => import('@routier/core/collections'),
    '@routier/core/errors': () => import('@routier/core/errors'),
    '@routier/core/expressions': () => import('@routier/core/expressions'),
    '@routier/core/performance': () => import('@routier/core/performance'),
    '@routier/core/pipeline': () => import('@routier/core/pipeline'),
    '@routier/core/plugins': () => import('@routier/core/plugins'),
    '@routier/core/results': () => import('@routier/core/results'),
    '@routier/core/schema': () => import('@routier/core/schema'),
    '@routier/core/transfer': () => import('@routier/core/transfer'),
    '@routier/core/types': () => import('@routier/core/types'),
    '@routier/core/utilities': () => import('@routier/core/utilities'),
    '@routier/datastore': () => import('@routier/datastore'),
    '@routier/react': () => import('@routier/react'),
    '@routier/memory-plugin': () => import('@routier/memory-plugin'),
    '@routier/browser-storage-plugin': () => import('@routier/browser-storage-plugin'),
    '@routier/dexie-plugin': () => import('@routier/dexie-plugin'),
    '@routier/sqlite-plugin': () => import('@routier/sqlite-plugin'),
    '@routier/pglite-plugin': () => import('@routier/pglite-plugin'),
    '@routier/pglite-plugin/browser-storage': () => import('@routier/pglite-plugin/browser-storage'),
    '@routier/devtools/production': () => import('@routier/devtools/production'),
    '../devtools': () => import('../devtools'),
};
