import { describe, expect, it } from "@jest/globals";
import { s } from "../schema/builder";
import type { InferType } from "../schema";

/**
 * Tests the code generated by the codegen handlers by running the compiled schema's
 * clone, serialize, deserialize, compare, and set functions. This is the recommended
 * way to test handler output: compile a schema and assert on runtime behavior rather
 * than inspecting generated source strings.
 */

describe("Generated handlers (clone, serialize, deserialize, compare, set)", () => {
    describe("clone", () => {
        it("returns deep copy of flat entity", () => {
            const schema = s.define("flat", {
                id: s.string().key(),
                name: s.string(),
                count: s.number(),
            }).compile();

            const entity = { id: "1", name: "a", count: 10 };
            const cloned = schema.clone(entity as InferType<typeof schema>);

            expect(cloned).toEqual(entity);
            expect(cloned).not.toBe(entity);
            // Primitives are copied by value; nested objects would be different refs
        });

        it("deep copies nested objects (two levels)", () => {
            const schema = s.define("nested", {
                id: s.string().key(),
                profile: s.object({
                    displayName: s.string(),
                    address: s.object({
                        city: s.string(),
                        zip: s.string(),
                    }),
                }),
            }).compile();

            type E = InferType<typeof schema>;
            const entity: E = {
                id: "1",
                profile: {
                    displayName: "Jane",
                    address: { city: "NYC", zip: "10001" },
                },
            };

            const cloned = schema.clone(entity);

            expect(cloned).toEqual(entity);
            expect(cloned.profile).not.toBe(entity.profile);
            expect(cloned.profile.address).not.toBe(entity.profile.address);
            cloned.profile.address.city = "LA";
            expect(entity.profile.address.city).toBe("NYC");
        });

        it("clones nested arrays", () => {
            const schema = s.define("withArray", {
                id: s.string().key(),
                tags: s.string().array(),
                meta: s.object({
                    items: s.number().array(),
                }),
            }).compile();

            type E = InferType<typeof schema>;
            const entity: E = {
                id: "1",
                tags: ["a", "b"],
                meta: { items: [1, 2, 3] },
            };

            const cloned = schema.clone(entity);

            expect(cloned.tags).toEqual(entity.tags);
            expect(cloned.tags).not.toBe(entity.tags);
            expect(cloned.meta.items).toEqual(entity.meta.items);
            expect(cloned.meta.items).not.toBe(entity.meta.items);
        });

        it("preserves optional nested when present", () => {
            const schema = s.define("optionalNested", {
                id: s.string().key(),
                profile: s.object({
                    name: s.string(),
                    avatar: s.string().optional(),
                }).optional(),
            }).compile();

            type E = InferType<typeof schema>;
            const withProfile: E = {
                id: "1",
                profile: { name: "J", avatar: undefined },
            };

            expect(schema.clone(withProfile)).toEqual(withProfile);
            expect(schema.clone(withProfile).profile).not.toBe(withProfile.profile);
        });
    });

    describe("serialize → deserialize round-trip", () => {
        it("round-trips flat entity", () => {
            const schema = s.define("flat", {
                id: s.string().key(),
                name: s.string(),
                count: s.number(),
            }).compile();

            type E = InferType<typeof schema>;
            const entity: E = { id: "1", name: "x", count: 5 };
            const round = schema.deserialize(schema.serialize(entity) as never);

            expect(round).toEqual(entity);
        });

        it("round-trips dates via custom deserializer", () => {
            const schema = s.define("withDate", {
                id: s.string().key(),
                createdAt: s.date().default(() => new Date()).deserialize((x) => new Date(x as string)),
            }).compile();

            type E = InferType<typeof schema>;
            const entity: E = { id: "1", createdAt: new Date("2024-06-15T12:00:00.000Z") };
            const serialized = schema.serialize(entity) as never;
            const round = schema.deserialize(serialized);

            expect(round.createdAt).toBeInstanceOf(Date);
            expect(round.createdAt.getTime()).toBe(entity.createdAt.getTime());
        });

        it("round-trips nested objects", () => {
            const schema = s.define("nested", {
                id: s.string().key(),
                profile: s.object({
                    name: s.string(),
                    address: s.object({
                        city: s.string(),
                    }),
                }),
            }).compile();

            type E = InferType<typeof schema>;
            const entity: E = {
                id: "1",
                profile: { name: "A", address: { city: "Boston" } },
            };
            const round = schema.deserialize(schema.serialize(entity) as never);

            expect(round).toEqual(entity);
        });
    });

    describe("compare", () => {
        it("returns true for equal flat entities", () => {
            const schema = s.define("flat", {
                id: s.string().key(),
                name: s.string(),
            }).compile();

            type E = InferType<typeof schema>;
            const a: E = { id: "1", name: "same" };
            const b: E = { id: "1", name: "same" };

            expect(schema.compare(a, b)).toBe(true);
        });

        it("returns false when values differ", () => {
            const schema = s.define("flat", {
                id: s.string().key(),
                name: s.string(),
            }).compile();

            type E = InferType<typeof schema>;
            const a: E = { id: "1", name: "a" };
            const b: E = { id: "1", name: "b" };

            expect(schema.compare(a, b)).toBe(false);
        });

        it("compares nested objects", () => {
            const schema = s.define("nested", {
                id: s.string().key(),
                profile: s.object({
                    city: s.string(),
                }),
            }).compile();

            type E = InferType<typeof schema>;
            const a: E = { id: "1", profile: { city: "NYC" } };
            const b: E = { id: "1", profile: { city: "NYC" } };
            const c: E = { id: "1", profile: { city: "LA" } };

            expect(schema.compare(a, b)).toBe(true);
            expect(schema.compare(a, c)).toBe(false);
        });

        it("compares dates by value", () => {
            const schema = s.define("withDate", {
                id: s.string().key(),
                at: s.date(),
            }).compile();

            type E = InferType<typeof schema>;
            const t = new Date("2024-01-01T00:00:00.000Z");
            const a: E = { id: "1", at: t };
            const b: E = { id: "1", at: new Date(t.getTime()) };

            expect(schema.compare(a, b)).toBe(true);
        });
    });

    describe("set", () => {
        it("copies source into destination (flat)", () => {
            const schema = s.define("flat", {
                id: s.string().key(),
                name: s.string(),
            }).compile();

            type E = InferType<typeof schema>;
            const dest: E = { id: "1", name: "old" };
            const source: E = { id: "1", name: "new" };

            schema.set(dest, source);

            expect(dest.name).toBe("new");
        });

        it("copies nested properties", () => {
            const schema = s.define("nested", {
                id: s.string().key(),
                profile: s.object({
                    city: s.string(),
                }),
            }).compile();

            type E = InferType<typeof schema>;
            const dest: E = { id: "1", profile: { city: "NYC" } };
            const source: E = { id: "1", profile: { city: "LA" } };

            schema.set(dest, source);

            expect(dest.profile.city).toBe("LA");
        });
    });
});
