import type { BlobStore } from './types';

/**
 * A blob store on the local filesystem.
 *
 * Node only, and its own entry point so a browser bundle never resolves `node:fs`:
 *
 * ```ts
 * import { fileSystemBlobStore } from '@routier/blob-plugin/stores/fileSystem';
 * ```
 *
 * Useful for a desktop application, a single-server deployment, and for developing against
 * something real before pointing at S3. It is not a substitute for object storage across
 * several machines: nothing here coordinates two processes writing the same key, and
 * content-addressing is what makes that safe rather than any locking.
 */
export const fileSystemBlobStore = (root: string): BlobStore => {
    /** Imported per call rather than at module scope so this file stays importable anywhere. */
    const node = async () => {
        const [fs, path] = await Promise.all([import('node:fs/promises'), import('node:path')]);

        return { fs, path };
    };

    /**
     * The absolute path for a key.
     *
     * Keys are generated by `blobKey` and contain only hex and slashes, but this is the one
     * place a caller-supplied key could escape the root, so it is checked rather than trusted.
     */
    const resolve = async (key: string) => {
        const { path } = await node();
        const full = path.resolve(root, key);
        const bounded = path.resolve(root);

        if (full !== bounded && full.startsWith(bounded + path.sep) === false) {
            throw new Error(`Blob key '${key}' resolves outside the store root.`);
        }

        return full;
    };

    return {
        name: `filesystem (${root})`,

        async put(key, bytes) {
            const { fs, path } = await node();
            const full = await resolve(key);

            await fs.mkdir(path.dirname(full), { recursive: true });

            // Written to a temporary name and renamed. A crash mid-write would otherwise
            // leave a short file at a content-addressed key — a key that promises those exact
            // bytes — and `has` would then report it present and skip the real upload forever.
            const temporary = `${full}.${Math.abs(hash(key))}.partial`;

            await fs.writeFile(temporary, bytes);
            await fs.rename(temporary, full);
        },

        async has(key) {
            const { fs } = await node();

            try {
                await fs.access(await resolve(key));
                return true;
            } catch {
                return false;
            }
        },

        async get(key) {
            const { fs } = await node();
            const buffer = await fs.readFile(await resolve(key));

            return new Uint8Array(buffer);
        },

        async delete(key) {
            const { fs } = await node();

            try {
                await fs.unlink(await resolve(key));
            } catch (error) {
                // Already gone is the desired state.
                if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
                    throw error;
                }
            }
        },

        async *list(prefix) {
            const { fs, path } = await node();
            const start = path.resolve(root);

            const walk = async function* (directory: string): AsyncGenerator<string> {
                let entries;

                try {
                    entries = await fs.readdir(directory, { withFileTypes: true });
                } catch {
                    // A store that has never been written to has no directory yet, which is
                    // an empty listing rather than an error.
                    return;
                }

                for (const entry of entries) {
                    const full = path.join(directory, entry.name);

                    if (entry.isDirectory()) {
                        yield* walk(full);
                        continue;
                    }

                    if (entry.name.endsWith('.partial')) {
                        continue;
                    }

                    yield path.relative(start, full).split(path.sep).join('/');
                }
            };

            for await (const key of walk(start)) {
                if (key.startsWith(prefix)) {
                    yield key;
                }
            }
        },
    };
};

/** A short stable suffix for a temporary file, so two writers do not collide on one name. */
const hash = (value: string) => {
    let result = 0;

    for (let i = 0; i < value.length; i++) {
        result = (result * 31 + value.charCodeAt(i)) | 0;
    }

    return result;
};
